# Generated by Django 4.0.1 on 2022-01-23 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(default='43701', max_length=5, validators=[django.core.validators.RegexValidator(message='Must be valid zipcode in formats from 00000 to 99999', regex='^\\d{5}$')]),
        ),
    ]
